### ISSUE TITLE
Very old lodash breaks when babel polyfill required

### ISSUE THREAD

**Issue by XeCycle** [cowboy/node-globule#16]
Babeljs polyfills changes some builtin objects & functions, which breaks _.isPlainObject.  Turned out that was fixed in lodash 2.4.1.  Can we update this dependency?

**Comment by AgentME** [comment]
Globule 0.2.0 has updated from using lodash ~1.0.1 to lodash ~2.4.1 already.

If you're having issues with gulp.watch, the problem is that gaze 0.5.1 depends on globule ~0.1.0. Gaze 0.6+ depend on globule ~0.2.0, but glob-watcher depends on Gaze ^0.5.1 and is [closing](https://github.com/wearefractal/glob-watcher/issues/10) [issues](https://github.com/wearefractal/glob-watcher/issues/12) about it.

One of the following needs to happen:
* globule backports the lodash dependency update and releases a version 0.1.1.
* gaze backports the globule dependency update and releases a version 0.5.2.
* lodash backports the getPrototypeOf fix and releases a version 1.0.2.
* glob-watcher updates its gaze dependency.
* babel changes its polyfill to make its Object.getPrototypeOf replacement look native to work around the ancient lodash issue. (... babel's polyfill is based on core-js, so they would probably need to get the fix pushed upstream...)

**Comment by XeCycle** [comment]
Ah that's nasty, sorry I did not track it down thoroughly.  From my point I'd say glob-watcher shall update its dependency.  Closing.

**Comment by AgentME** [comment]
glob-watcher is currently choosing to stay on gaze ^0.5.1.
