### ISSUE TITLE
Glob dependency update required

### ISSUE THREAD

**Issue by RandTrawick** [cowboy/node-globule#30]
"glob": "~3.1.21" gives a Error: ENOTSUP: operation not supported on socket on networked drives.

Updated glob fixed this issue.
Please update Glob dependency.

**Comment by denysvitali** [comment]
There is also a warning about graceful-fs (which depends on glob),
please update it ASAP since the graceful-fs versions before 4.0 aren't supported by newest node versions.

`npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`

**Comment by shama** [comment]
Fixed on 1c6b40d5b397729be1a79b5737251aa83549e3b0
